syntax = "proto3";

option csharp_namespace = "AstroServer";

package astro;

// Service definition
service AstroService {
  rpc StarVelocity (StarVelocityRequest) returns (AstroReply);
  rpc StarDistance (StarDistanceRequest) returns (AstroReply);
  rpc CelsiusToKelvin (TemperatureRequest) returns (AstroReply);
  rpc BlackholeEventHorizon (BlackholeRequest) returns (AstroReply);
}

// Request messages
message StarVelocityRequest {
	double observedWavelength = 1;
	double restWavelength = 2;
}

message StarDistanceRequest {
	double parallaxAngle = 1;
}

message TemperatureRequest {
	double celsius = 1;
}

message BlackholeRequest {  
	double mass = 1;
}

// Common response
message AstroReply {
	double result = 1;
	string message = 2;
}